{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "konsear.serviceAccountName" . }}
  labels:
{{ include "konsear.labels" . | indent 4 }}
{{- end -}}
